import React, { useState } from "react";
import { FilePlus, Download, Printer, X, Eye, FileText, CheckCircle2, Clock, ChevronDown } from "lucide-react";
import {
  LineChart,
  Line,
  BarChart,
  Bar,
  PieChart,
  Pie,
  Cell,
  ResponsiveContainer,
  XAxis,
  YAxis,
  Tooltip,
  Legend,
  CartesianGrid,
} from "recharts";
import { Panel, StatusBadge, StatCard } from "../components/ui";

const revenueExpense = [
  { week: "W1", revenue: 42000, expense: 30000 },
  { week: "W2", revenue: 45000, expense: 31000 },
  { week: "W3", revenue: 40000, expense: 29500 },
  { week: "W4", revenue: 48000, expense: 32000 },
  { week: "W5", revenue: 46000, expense: 31500 },
];

const financialBreakdown = [
  { name: "Fuel Sales", value: 55, color: "#0ea5e9" },
  { name: "Store Sales", value: 25, color: "#f59e0b" },
  { name: "Service & Maintenance", value: 12, color: "#10b981" },
  { name: "Other Revenue", value: 8, color: "#6366f1" },
];

const paymentMethod = [
  { week: "W1", card: 1800, cash: 1200, qr: 900 },
  { week: "W2", card: 2000, cash: 1300, qr: 1000 },
  { week: "W3", card: 1700, cash: 1100, qr: 950 },
  { week: "W4", card: 2200, cash: 1400, qr: 1050 },
];

const storeCategory = [
  { name: "North Branch", value: 30, color: "#0ea5e9" },
  { name: "South Branch", value: 25, color: "#f59e0b" },
  { name: "East Branch", value: 25, color: "#10b981" },
  { name: "West Branch", value: 20, color: "#6366f1" },
];

const initialReports = [
  { id: "#REP-002", title: "Integrated Q4 Sales & Finance", period: "Q4 2026", location: "Main Station (#ST-001)", by: "Sok Piseth", date: "2026-08-11", status: "Completed" },
  { id: "#REP-003", title: "Integrated Q4 Fuel Management", period: "Q4 2026", location: "Main Station (#ST-001)", by: "Keo Vannet", date: "2026-08-16", status: "In Progress" },
  { id: "#REP-004", title: "Integrated Q4 Employee Attendance", period: "Q4 2026", location: "Main Station (#ST-001)", by: "Chhay Nin", date: "2026-08-18", status: "Completed" },
  { id: "#REP-005", title: "Integrated Q4 Inventory Audit", period: "Q4 2026", location: "Main Station (#ST-001)", by: "Sok Piseth", date: "2026-08-20", status: "Completed" },
];

export default function MasterReports() {
  const [reports, setReports] = useState(initialReports);
  const [isAddModalOpen, setIsAddModalOpen] = useState(false);
  const [selectedReport, setSelectedReport] = useState(null);
  const [showExportMenu, setShowExportMenu] = useState(false);

  // New Report Form State
  const [newReport, setNewReport] = useState({
    title: "",
    period: "Q4 2026",
    location: "Main Station (#ST-001)",
    by: "",
    status: "Completed",
  });

  // Handle Add Report
  const handleAddReport = (e) => {
    e.preventDefault();
    if (!newReport.title || !newReport.by) return;

    const nextId = `#REP-00${reports.length + 2}`;
    const today = new Date().toISOString().split("T")[0];

    const added = {
      id: nextId,
      ...newReport,
      date: today,
    };

    setReports([added, ...reports]);
    setNewReport({ title: "", period: "Q4 2026", location: "Main Station (#ST-001)", by: "", status: "Completed" });
    setIsAddModalOpen(false);
  };

  // Export Table to CSV
  const handleExportCSV = () => {
    const headers = ["Report ID,Report Title,Period,Location,Generated By,Date,Status\n"];
    const rows = reports.map((r) => `${r.id},"${r.title}",${r.period},"${r.location}",${r.by},${r.date},${r.status}`).join("\n");
    const blob = new Blob([headers + rows], { type: "text/csv" });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `Master_Report_${new Date().toISOString().split("T")[0]}.csv`;
    a.click();
    setShowExportMenu(false);
  };

  // Handle Print Page
  const handlePrint = () => {
    window.print();
  };

  // Download Single Report Item JSON
  const handleDownloadReport = (report) => {
    const dataStr = "data:text/json;charset=utf-8," + encodeURIComponent(JSON.stringify(report, null, 2));
    const downloadAnchor = document.createElement("a");
    downloadAnchor.setAttribute("href", dataStr);
    downloadAnchor.setAttribute("download", `${report.id}_Summary.json`);
    document.body.appendChild(downloadAnchor);
    downloadAnchor.click();
    downloadAnchor.remove();
  };

  return (
    <div className="space-y-5 p-6 bg-slate-50/60 min-h-screen">
      {/* Header Bar */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3">
        <div>
          <h2 className="text-lg font-bold text-slate-800 tracking-tight">Master Report</h2>
          <p className="text-xs text-slate-400">Integrated financial analytics, inventory, and station performance overview</p>
        </div>
        <div className="flex items-center gap-2 print:hidden">
          <button
            onClick={() => setIsAddModalOpen(true)}
            className="flex items-center gap-1.5 rounded-xl bg-cyan-500 px-3.5 py-2 text-xs font-semibold text-white shadow-sm hover:bg-cyan-600 transition"
          >
            <FilePlus size={15} /> Add New Report
          </button>

          {/* Export Dropdown */}
          <div className="relative">
            <button
              onClick={() => setShowExportMenu(!showExportMenu)}
              className="flex items-center gap-1.5 rounded-xl border border-slate-200 bg-white px-3.5 py-2 text-xs font-semibold text-slate-600 shadow-sm hover:bg-slate-50 transition"
            >
              <Download size={15} /> Export (PDF/Excel) <ChevronDown size={13} />
            </button>
            {showExportMenu && (
              <div className="absolute right-0 mt-1.5 w-44 bg-white rounded-xl shadow-lg border border-slate-100 py-1 z-30 text-xs">
                <button
                  onClick={handleExportCSV}
                  className="w-full text-left px-3 py-2 text-slate-700 hover:bg-slate-50 flex items-center gap-2"
                >
                  <FileText size={14} className="text-emerald-500" /> Export Excel (.CSV)
                </button>
                <button
                  onClick={handlePrint}
                  className="w-full text-left px-3 py-2 text-slate-700 hover:bg-slate-50 flex items-center gap-2"
                >
                  <Printer size={14} className="text-cyan-500" /> Save as PDF (Print)
                </button>
              </div>
            )}
          </div>

          <button
            onClick={handlePrint}
            className="flex items-center gap-1.5 rounded-xl border border-slate-200 bg-white px-3.5 py-2 text-xs font-semibold text-slate-600 shadow-sm hover:bg-slate-50 transition"
          >
            <Printer size={15} /> Print
          </button>
        </div>
      </div>

      {/* Metric Cards */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
        <StatCard label="Total Fuel Sales ($)" value="$150,250.00" delta="+12% vs Q3" deltaTone="up" />
        <StatCard label="Store Sale ($)" value="$45,780.50" delta="+5% vs Q3" deltaTone="up" />
        <StatCard label="Total Expenses ($)" value="$98,120.00" delta="-2% lower" deltaTone="neutral" />
        <StatCard label="Net Profit ($)" value="$97,910.50" delta="+18% profit margin" deltaTone="up" />
      </div>

      {/* Row 1 Charts */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
        <Panel title="Station Integrated Overview (Q4 2026) — Integrated Revenue vs Multi-layered Expenses">
          <ResponsiveContainer width="100%" height={210}>
            <LineChart data={revenueExpense}>
              <CartesianGrid strokeDasharray="3 3" stroke="#f1f5f9" />
              <XAxis dataKey="week" tick={{ fontSize: 11, fill: "#94a3b8" }} axisLine={false} tickLine={false} />
              <YAxis tick={{ fontSize: 11, fill: "#94a3b8" }} axisLine={false} tickLine={false} />
              <Tooltip />
              <Legend wrapperStyle={{ fontSize: 11 }} />
              <Line type="monotone" dataKey="revenue" name="Revenue" stroke="#0ea5e9" strokeWidth={3} dot={{ r: 3 }} />
              <Line type="monotone" dataKey="expense" name="Expenses" stroke="#f43f5e" strokeWidth={2.5} dot={{ r: 3 }} />
            </LineChart>
          </ResponsiveContainer>
        </Panel>

        <Panel title="Overall Performance — Financial Breakdown & Operations Details">
          <div className="grid grid-cols-3 gap-2 text-center text-xs mb-3 bg-slate-50/80 p-2.5 rounded-xl border border-slate-100">
            <div>
              <div className="text-slate-400">Avg. Wait Time</div>
              <div className="font-bold text-slate-700 text-sm">12 min</div>
            </div>
            <div>
              <div className="text-slate-400">Gallons per Hour</div>
              <div className="font-bold text-slate-700 text-sm">36 Gal</div>
            </div>
            <div>
              <div className="text-slate-400">Tank Levels %</div>
              <div className="font-bold text-emerald-600 text-sm">85%</div>
            </div>
          </div>
          <ResponsiveContainer width="100%" height={145}>
            <PieChart>
              <Pie data={financialBreakdown} dataKey="value" nameKey="name" innerRadius={38} outerRadius={58} paddingAngle={3}>
                {financialBreakdown.map((f) => (
                  <Cell key={f.name} fill={f.color} />
                ))}
              </Pie>
              <Tooltip />
              <Legend wrapperStyle={{ fontSize: 10 }} />
            </PieChart>
          </ResponsiveContainer>
        </Panel>
      </div>

      {/* Row 2 Charts */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
        <Panel title="Sales Breakdown by Payment Method">
          <ResponsiveContainer width="100%" height={190}>
            <BarChart data={paymentMethod}>
              <CartesianGrid strokeDasharray="3 3" stroke="#f1f5f9" />
              <XAxis dataKey="week" tick={{ fontSize: 11, fill: "#94a3b8" }} axisLine={false} tickLine={false} />
              <YAxis tick={{ fontSize: 11, fill: "#94a3b8" }} axisLine={false} tickLine={false} />
              <Tooltip />
              <Legend wrapperStyle={{ fontSize: 11 }} />
              <Bar dataKey="card" name="Card" stackId="a" fill="#0ea5e9" radius={[0, 0, 0, 0]} />
              <Bar dataKey="cash" name="Cash" stackId="a" fill="#f59e0b" radius={[0, 0, 0, 0]} />
              <Bar dataKey="qr" name="QR Code" stackId="a" fill="#10b981" radius={[4, 4, 0, 0]} />
            </BarChart>
          </ResponsiveContainer>
        </Panel>

        <Panel title="Convenience Store Top Categories by Region">
          <ResponsiveContainer width="100%" height={190}>
            <PieChart>
              <Pie data={storeCategory} dataKey="value" nameKey="name" innerRadius={42} outerRadius={68} paddingAngle={3}>
                {storeCategory.map((s) => (
                  <Cell key={s.name} fill={s.color} />
                ))}
              </Pie>
              <Tooltip />
              <Legend wrapperStyle={{ fontSize: 11 }} />
            </PieChart>
          </ResponsiveContainer>
        </Panel>
      </div>

      {/* Master Audit Log Table */}
      <Panel title="Audit-Level Master Report Log Table">
        <div className="overflow-x-auto">
          <table className="w-full text-left text-xs">
            <thead>
              <tr className="border-b border-slate-100 bg-slate-50/80 text-slate-400">
                <th className="px-3.5 py-2.5 font-semibold">Report ID</th>
                <th className="px-3.5 py-2.5 font-semibold">Report Type & Period</th>
                <th className="px-3.5 py-2.5 font-semibold">Location Context</th>
                <th className="px-3.5 py-2.5 font-semibold">Generated By</th>
                <th className="px-3.5 py-2.5 font-semibold">Date</th>
                <th className="px-3.5 py-2.5 font-semibold">Status</th>
                <th className="px-3.5 py-2.5 font-semibold text-right">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-50">
              {reports.map((r) => (
                <tr key={r.id} className="hover:bg-slate-50/70 transition">
                  <td className="px-3.5 py-2.5 font-semibold text-slate-800 font-mono">{r.id}</td>
                  <td className="px-3.5 py-2.5">
                    <div className="font-semibold text-slate-700">{r.title}</div>
                    <div className="text-[10px] text-slate-400">{r.period}</div>
                  </td>
                  <td className="px-3.5 py-2.5 text-slate-500">{r.location}</td>
                  <td className="px-3.5 py-2.5 font-medium text-slate-600">{r.by}</td>
                  <td className="px-3.5 py-2.5 text-slate-500">{r.date}</td>
                  <td className="px-3.5 py-2.5">
                    <StatusBadge status={r.status === "Completed" ? "Active" : "Check Status"} />
                  </td>
                  <td className="px-3.5 py-2.5 text-right font-medium space-x-2">
                    <button
                      onClick={() => setSelectedReport(r)}
                      className="text-cyan-600 hover:text-cyan-700 hover:underline"
                    >
                      View
                    </button>
                    <span className="text-slate-300">·</span>
                    <button
                      onClick={() => handleDownloadReport(r)}
                      className="text-cyan-600 hover:text-cyan-700 hover:underline"
                    >
                      Download
                    </button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </Panel>

      {/* Modal 1: Add New Report Modal */}
      {isAddModalOpen && (
        <div className="fixed inset-0 bg-slate-900/40 backdrop-blur-sm z-50 flex items-center justify-center p-4">
          <div className="bg-white rounded-2xl max-w-md w-full p-5 shadow-2xl border border-slate-100 space-y-4">
            <div className="flex justify-between items-center border-b pb-3">
              <h3 className="font-bold text-slate-800 text-sm">Generate New Master Report</h3>
              <button onClick={() => setIsAddModalOpen(false)} className="text-slate-400 hover:text-slate-600">
                <X size={18} />
              </button>
            </div>
            <form onSubmit={handleAddReport} className="space-y-3 text-xs">
              <div>
                <label className="block text-slate-600 mb-1 font-medium">Report Title / Type *</label>
                <input
                  type="text"
                  required
                  placeholder="e.g. Integrated Q4 Financial & Fuel Audit"
                  value={newReport.title}
                  onChange={(e) => setNewReport({ ...newReport, title: e.target.value })}
                  className="w-full border rounded-xl p-2.5 bg-slate-50 text-slate-800 outline-none focus:border-cyan-500"
                />
              </div>
              <div className="grid grid-cols-2 gap-2">
                <div>
                  <label className="block text-slate-600 mb-1 font-medium">Period</label>
                  <input
                    type="text"
                    value={newReport.period}
                    onChange={(e) => setNewReport({ ...newReport, period: e.target.value })}
                    className="w-full border rounded-xl p-2.5 bg-slate-50 text-slate-800 outline-none focus:border-cyan-500"
                  />
                </div>
                <div>
                  <label className="block text-slate-600 mb-1 font-medium">Status</label>
                  <select
                    value={newReport.status}
                    onChange={(e) => setNewReport({ ...newReport, status: e.target.value })}
                    className="w-full border rounded-xl p-2.5 bg-slate-50 text-slate-800 outline-none focus:border-cyan-500"
                  >
                    <option value="Completed">Completed</option>
                    <option value="In Progress">In Progress</option>
                  </select>
                </div>
              </div>
              <div>
                <label className="block text-slate-600 mb-1 font-medium">Location Context</label>
                <input
                  type="text"
                  value={newReport.location}
                  onChange={(e) => setNewReport({ ...newReport, location: e.target.value })}
                  className="w-full border rounded-xl p-2.5 bg-slate-50 text-slate-800 outline-none focus:border-cyan-500"
                />
              </div>
              <div>
                <label className="block text-slate-600 mb-1 font-medium">Generated By (Author) *</label>
                <input
                  type="text"
                  required
                  placeholder="e.g. Sok Piseth"
                  value={newReport.by}
                  onChange={(e) => setNewReport({ ...newReport, by: e.target.value })}
                  className="w-full border rounded-xl p-2.5 bg-slate-50 text-slate-800 outline-none focus:border-cyan-500"
                />
              </div>
              <div className="flex justify-end gap-2 pt-3">
                <button
                  type="button"
                  onClick={() => setIsAddModalOpen(false)}
                  className="px-4 py-2 border rounded-xl text-slate-600 font-medium"
                >
                  Cancel
                </button>
                <button type="submit" className="px-4 py-2 bg-cyan-500 text-white rounded-xl font-semibold hover:bg-cyan-600 shadow-sm">
                  Generate Report
                </button>
              </div>
            </form>
          </div>
        </div>
      )}

      {/* Modal 2: View Report Detail Modal */}
      {selectedReport && (
        <div className="fixed inset-0 bg-slate-900/40 backdrop-blur-sm z-50 flex items-center justify-center p-4">
          <div className="bg-white rounded-2xl max-w-md w-full p-5 shadow-2xl border border-slate-100 space-y-4">
            <div className="flex justify-between items-center border-b pb-3">
              <div className="flex items-center gap-2">
                <FileText className="text-cyan-500" size={18} />
                <h3 className="font-bold text-slate-800 text-sm">Report Details ({selectedReport.id})</h3>
              </div>
              <button onClick={() => setSelectedReport(null)} className="text-slate-400 hover:text-slate-600">
                <X size={18} />
              </button>
            </div>

            <div className="space-y-3 text-xs bg-slate-50 p-4 rounded-xl border border-slate-100">
              <div>
                <span className="text-slate-400 block">Report Title:</span>
                <span className="font-bold text-slate-800 text-sm">{selectedReport.title}</span>
              </div>
              <div className="grid grid-cols-2 gap-2">
                <div>
                  <span className="text-slate-400 block">Time Period:</span>
                  <span className="font-semibold text-slate-700">{selectedReport.period}</span>
                </div>
                <div>
                  <span className="text-slate-400 block">Report Status:</span>
                  <StatusBadge status={selectedReport.status === "Completed" ? "Active" : "Check Status"} />
                </div>
              </div>
              <div>
                <span className="text-slate-400 block">Station Location:</span>
                <span className="font-semibold text-slate-700">{selectedReport.location}</span>
              </div>
              <div className="grid grid-cols-2 gap-2">
                <div>
                  <span className="text-slate-400 block">Generated By:</span>
                  <span className="font-semibold text-slate-700">{selectedReport.by}</span>
                </div>
                <div>
                  <span className="text-slate-400 block">Date Generated:</span>
                  <span className="font-semibold text-slate-700">{selectedReport.date}</span>
                </div>
              </div>
            </div>

            <div className="flex justify-end gap-2 pt-2">
              <button
                onClick={() => handleDownloadReport(selectedReport)}
                className="flex items-center gap-1.5 px-4 py-2 bg-cyan-500 text-white rounded-xl font-semibold hover:bg-cyan-600 text-xs shadow-sm"
              >
                <Download size={14} /> Download File
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}